
import { Member } from "../types";

const MEMBERS_KEY = "jofc_enna_members_v1";

// Lista iniziale basata sui dati forniti
const INITIAL_MEMBERS_DATA: {name: string, birthDate?: string}[] = [
  { name: "Russo Michele", birthDate: "1991-08-25" },
  { name: "Ferro Angelo" },
  { name: "Ferro Mattia" },
  { name: "Di Bella Ugo" },
  { name: "Lombardo Luciano" },
  { name: "Lombardo Mirko" },
  { name: "Andolina Luca" },
  { name: "Bertino Salvatore" },
  { name: "Vullo Salvatore" },
  { name: "Vullo Giovanni Maria" },
  { name: "Vicari Maria Stefania" },
  { name: "Di Franco Samantha Maria" },
  { name: "Sanfilippo Carlo Federico G." },
  { name: "Sanfilippo Diego" },
  { name: "Ballistreri Alessio" },
  { name: "Giliberto Angelo" },
  { name: "Lucchese Mario" },
  { name: "Arnaldi Micaela" },
  { name: "Lucchese Sonia" },
  { name: "Lattarico Francesco" },
  { name: "Bumbaca Saverio" },
  { name: "D'Agostino Anna Maria" },
  { name: "Passalacqua Ferruccio" },
  { name: "Passalacqua Francesco" },
  { name: "Costa Riccardo Maria" },
  { name: "Costa Davide" },
  { name: "Salvaggio Giuliana Maria" },
  { name: "Gervasi Paolo" },
  { name: "Di Marco Giuseppe" },
  { name: "Di Marco Salvatore" },
  { name: "Taormina David" },
  { name: "Passalacqua Raffaele" },
  { name: "Sicurezza Paolo" },
  { name: "Sicurezza Fsco Paolo" },
  { name: "Sicurezza Marco" },
  { name: "Sicurezza Stefania" },
  { name: "Manusè Giulia", birthDate: "2011-02-19" },
  { name: "Manusè Marco" },
  { name: "Sicurezza Giuseppe" },
  { name: "Tosetto Giuseppe" },
  { name: "D'Alù Angelo Domenico" },
  { name: "Dal Piva Simone" },
  { name: "Gruttadauria Miki Francesco" },
  { name: "Gruttadauria Josephine Lucy" },
  { name: "Gueli Asia" },
  { name: "Geraci Leandro" },
  { name: "Geraci Mirko" },
  { name: "Battaglia Cesare" },
  { name: "Castro Carmelo" },
  { name: "Arena Giancarlo" },
  { name: "Carta Libera" },
  { name: "Arena Roberto" },
  { name: "Arena Giuliana" },
  { name: "Puglia Michelangelo" },
  { name: "Di Fina Santo" },
  { name: "Di Fina Sebastiano" },
  { name: "Calì Antonio" },
  { name: "Favale Matteo" },
  { name: "Mingrino Luciano" },
  { name: "Cannarozzo Paolo" },
  { name: "Guglielmaci Guido" },
  { name: "Cristaldi Vincenzo" },
  { name: "La Manna Damiano" },
  { name: "Alessandra Luigi Pasquale" },
  { name: "Mantegna Francesco" },
  { name: "De Rose Carmelo" },
  { name: "De Rose Ezio" },
  { name: "De Rose Giuseppe" },
  { name: "Miserendino Matteo" },
  { name: "Ambra Laura", birthDate: "1970-02-16" },
  { name: "Rivoli Salvatore" },
  { name: "Faggiano Francesca" },
  { name: "Rivoli Mario" },
  { name: "Laiosa Valerio" },
  { name: "Oglialoro Giulia" },
  { name: "Canerini Calogero" },
  { name: "Di Fede Maria Concetta" },
  { name: "Nicosia Gaetano" },
  { name: "Calì Giulia" },
  { name: "Calì Gabriele" },
  { name: "Lo Porto Giuseppe" },
  { name: "Sulsenti Vincenzo" },
  { name: "Cannarozzo Sebastiano" },
  { name: "Patelmo Mario" },
  { name: "Mangione Simone" },
  { name: "Savoca Sebastiano Primo" },
  { name: "Di Fabrizio Davide Neva" },
  { name: "Minardi Carmelo" },
  { name: "Di Bella Giuliana" },
  { name: "Primavera Tea" },
  { name: "Primavera Clara" },
  { name: "Perna Giovanni Biagio" },
  { name: "Rizzo Alberto" },
  { name: "Guasto Antonio" },
  { name: "Pavano Giovanni" },
  { name: "Pavano Rosario" },
  { name: "Zarrelli Armando" },
  { name: "Agozzino Silvestro" },
  { name: "Acciaro Giuseppe" },
  { name: "Fileccia Samuele" },
  { name: "Cimino Gaetano" },
  { name: "Morgano Giuseppe" },
  { name: "Severino Paolo" },
  { name: "Serra Pierluigi" },
  { name: "Serra Salvatore" },
  { name: "Campisi Vincenzo" },
  { name: "Campione Alessio" },
  { name: "Di Barca Gaetano" },
  { name: "Puglisi Hermes" },
  { name: "Testaì Giuseppe" },
  { name: "Vitale Giuseppe" },
  { name: "Billanti Samuel Mario" },
  { name: "Rimoldi Manuel" },
  { name: "Cucco Stefano" },
  { name: "Ragona Vincenzo" },
  { name: "Ragona Mattia" },
  { name: "Ragona Ivan Luciano" },
  { name: "Iannello Luca Pio" },
  { name: "Schmaus Thomas" },
  { name: "Nasello Mario Antonino" },
  { name: "Colaleo Maurizio" },
  { name: "Nicosia Carmelo Piero" },
  { name: "Nicosia Mario" },
  { name: "Calascibetta Santo" },
  { name: "Gruttadauria Aida" },
  { name: "Coniglione Cristian" },
  { name: "Ginepri Azzurra" },
  { name: "Oliveri Gemma Maria" },
  { name: "Saltaleggio Emmanuel" },
  { name: "Macaluso Andrea" },
  { name: "Di Dio Mattia Giovanni" },
  { name: "Termine Giovanni" },
  { name: "Sicurezza Massimo" },
  { name: "Andolina Paolo" },
  { name: "Baldi Enrico" },
  { name: "Micali Marco" },
  { name: "Hashemizdehnaeini Shabnam" },
  { name: "Milano Vincenzo" },
  { name: "Calì Christian" },
  { name: "Placenti Simona" },
  { name: "Gervasi Alessandro" },
  { name: "Greca Roberto" },
  { name: "Ciccio Salvatore" },
  { name: "Alaimo Davide" },
  { name: "Contraffatto Federico" },
  { name: "Lahmice Abdellatif" },
  { name: "Giangreco Simone" },
  { name: "Giangreco Elisabetta" },
  { name: "Gervasi Ilaria" },
  { name: "Bonasera Fabrizio" },
  { name: "Randazzo Desirè" },
  { name: "Piazza Giuseppe" },
  { name: "Giunta Danilo Orazio" },
  { name: "Rossignolo Sebastiano" },
  { name: "Farina Salvatore Luca" },
  { name: "Giannone Calogero" },
  { name: "Giannone Samuele" },
  { name: "Palmeri Maurizio", birthDate: "1955-02-28" },
  { name: "Di Prima Giuseppe" },
  { name: "Di Prima Mario" },
  { name: "De Santis Jessica", birthDate: "1990-02-22" },
  { name: "Nasonte Massimiliano" },
  { name: "Nasonte Saverio" },
  { name: "Passalacqua Filippo" },
  { name: "Cristaldi Bruno Michael" },
  { name: "Mangione Emanuele" },
  { name: "Borghese Francesco" },
  { name: "Di Franco Giuseppe" },
  { name: "Piazza Giuseppe" },
  { name: "Milano Stefano" },
  { name: "Americo Lorenzo" },
  { name: "Americo Tommaso" },
  { name: "Ferraro Gianluca" },
  { name: "Ferraro Francesco" },
  { name: "Berna Nasca Giacomo" },
  { name: "Benvegna Melania" },
  { name: "La Cognata Giuseppe" },
  { name: "Costarelli Jhonny" },
  { name: "Costarelli Matthias" },
  { name: "D'Alù Ivan" },
  { name: "Benvegna Marzia Ambra" },
  { name: "Tchouyo Yakam Ivan Francesco" },
  { name: "La Delia Carmelo" },
  { name: "La Delia Giuseppe" },
  { name: "Micali Matteo" },
  { name: "Sgrò Francesco Lucio" },
  { name: "Sgrò Leonardo" },
  { name: "Schembri Rosaria" },
  { name: "Sgrò Serena" },
  { name: "Campanile Eleonora Maria" },
  { name: "Vigni Antonino" },
  { name: "Greco Giuseppe" },
  { name: "Napoli Matteo" },
  { name: "Librizzi Daniele" },
  { name: "Barreca Danilo" },
  { name: "Buscemi Davide" },
  { name: "Di Dio Randazzo Stefano" },
  { name: "Di Dio Randazzo Andrea" },
  { name: "Di Dio Randazzo Francesco" },
  { name: "Gervasi Francesco Aldo" },
  { name: "Lianzi Sandro" },
  { name: "Di Rosa Fabio" },
  { name: "Di Rosa Marta Maria" },
  { name: "Buscemi Biagio" },
  { name: "Timpanaro Siria Antonia" },
  { name: "Lunardo Vincenzo" },
  { name: "Merulla Pamela" }
];

export const getMembers = (): Member[] => {
  const saved = localStorage.getItem(MEMBERS_KEY);
  if (saved) {
    try {
      const parsed = JSON.parse(saved);
      // Se la lista salvata è vuota o molto più corta di quella iniziale (reset manuale o errore), 
      // ricarichiamo quella iniziale per sicurezza, ma solo se siamo in dev o per fix. 
      // Qui ci fidiamo del localStorage se esiste, altrimenti usiamo INITIAL_MEMBERS_DATA
      if (parsed.length > 0) return parsed;
    } catch (e) {
      console.error("Errore parsing soci", e);
    }
  }
  
  const initial: Member[] = INITIAL_MEMBERS_DATA.map((item, index) => ({
    id: `m-${index}`,
    name: item.name,
    birthDate: item.birthDate || ""
  }));
  
  // Salviamo subito per popolarlo la prima volta
  saveMembers(initial);
  return initial;
};

export const saveMembers = (members: Member[]) => {
  localStorage.setItem(MEMBERS_KEY, JSON.stringify(members));
};

export const getBirthdaysToday = (): string[] => {
  const members = getMembers();
  const today = new Date();
  const monthDay = `${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`;
  
  return members
    .filter(m => m.birthDate && m.birthDate.endsWith(monthDay))
    .map(m => m.name.toUpperCase());
};
